version: '3.3'

services:
  node:
    container_name: tippy_node
    image: node
    ports:
      - '3000:3000'
    env_file:
      - .env
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app
    links:
      - db
    networks:
      - tippy
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'

  db:
    container_name: tippy_db
    image: postgres
    ports:
      - 5432:5432
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - tippy

  adminer:
    container_name: tippy_adminer
    image: adminer
    ports:
      - '8888:8080'
    environment:
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - db
    restart: always
    networks:
      - tippy

networks:
  tippy:
    driver: bridge
