swagger: '2.0'
info:
  title: TIPPY API
  description: 'Documentation of an Tippy Open Source API that allows restaurant
    owners to manage tips and redistribute them fairly.'
  version: 1.0.0
paths:
  /users:
    get:
      tags:
        - Users
      responses:
        200:
          description: 'Returns a list of users.'
          schema:
            type: object
            items:
              $ref: '#/definitions/User'

definitions:
  User:
    type: object
    required:
      - firstname
      - lastname
      - status
    properties:
      id:
        type: integer
        format: int64
      firstname:
        type: string
      lastname:
        type: string
      balance:
        type: number
        format: float
      status:
        type: boolean
        description: 'User position (false = kitchen, true = service)'
      active:
        type: boolean
        description: 'User status (false = inactive, true = active)'
      created_at:
        type: string
        format: date-time
      modified_at:
        type: string
        format: date-time
      shifts:
        type: array
        items:
          $ref: '#/components/schemas/Shift'
      payments:
        type: array
        items:
          $ref: '#/components/schemas/Payment'
  Shift:
    type: object
    required:
      - type
    properties:
      id:
        type: integer
        format: int64
      type:
        type: string
        description: 'Shift type (0 = day, 1 = night)'
      is_closed:
        type: boolean
        default: false
      created_at:
        type: string
        format: date-time
      modified_at:
        type: string
        format: date-time
      users:
        type: array
        items:
          $ref: '#/components/schemas/User'
      tips:
        type: array
        items:
          $ref: '#/components/schemas/Tip'
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
